// Generated by CoffeeScript 1.8.0
var ng;

ng = angular;

ng.module('cssdesk.services', []);

ng.module('cssdesk.controllers', []);

ng.module('cssdesk.directives', []);

ng.module('cssdesk.filters', []);

ng.module('cssdesk', ['cssdesk.services', 'cssdesk.controllers', 'cssdesk.directives', 'cssdesk.filters']);
