// Generated by CoffeeScript 1.8.0
ng.module('cssdesk.controllers').controller('slidesCtrl', [
  '$scope', function($scope) {
    var links, selector, setComboStyle, setStyle;
    $scope.flexDirections = ['row', 'row-reverse', 'column', 'column-reverse'];
    $scope.alignItems = ['flex-start', 'flex-end', 'center', 'baseline', 'stretch'];
    $scope.flexDirection = $scope.flexDirections[0];
    $scope.alignItem = $scope.alignItems[0];
    $scope.directionContainer = {
      'flexDirection': $scope.flexDirections[0],
      'alignItem': $scope.alignItems[0]
    };
    $scope.directionStyle = {
      'flex-direction': 'row'
    };
    $scope.alignStyle = {
      'align-items': 'flex-start'
    };
    $scope.directionContainerStyle = {
      'flex-direction': 'row',
      'align-items': 'flex-start'
    };
    links = [
      {
        "style": 'flex-direction',
        "value": "flexDirection"
      }, {
        "style": 'align-items',
        "value": "alignItem"
      }, {
        "style": ["flex-direction", "align-items"],
        "value": "directionStyle"
      }
    ];
    selector = function(elem, scope) {
      var elemScope;
      if (scope == null) {
        elemScope = document;
      } else {
        elemScope = document.querySelector(scope);
      }
      return elemScope.querySelectorAll(elem);
    };
    setStyle = function(link, val, ctrl) {
      var style;
      style = _.find(links, {
        "value": link
      }).style;
      ctrl["" + style] = val;
      return '';
    };
    setComboStyle = function(link, val, ctrl) {
      _.forEach(val, function(value, key) {
        return setStyle(key, value, ctrl);
      });
      return '';
    };
    $scope.$watch('flexDirection', function(newVal, oldVal) {
      if (newVal === oldVal) {
        return;
      }
      return setStyle('flexDirection', newVal, $scope.directionStyle);
    });
    $scope.$watch('alignItem', function(newVal, oldVal) {
      if (newVal === oldVal) {
        return;
      }
      return setStyle('alignItem', newVal, $scope.alignStyle);
    });
    return $scope.$watch('directionContainer', function(newVal, oldVal) {
      if (newVal === oldVal) {
        return;
      }
      return setComboStyle('directionStyle', newVal, $scope.directionContainerStyle);
    }, true);
  }
]);
